# Generated by Django 4.2.27 on 2026-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_order_delivery_otp_order_pickup_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password_plain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
