# Generated by Django 5.2.11 on 2026-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_restaurant_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
