# Generated by Django 5.2.11 on 2026-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_order_online_amount_order_refund_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Credit/Debit Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('COD', 'Cash on Delivery'), ('RAZORPAY', 'Razorpay')], max_length=20),
        ),
    ]
