# Generated by Django 5.2.11 on 2026-02-03 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_order_platform_fee_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI ID')], max_length=10)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Payment Method',
                'verbose_name_plural': 'Saved Payment Methods',
                'db_table': 'saved_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='FavouriteMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_menu_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite Menu Item',
                'verbose_name_plural': 'Favourite Menu Items',
                'db_table': 'user_favourite_menu_items',
                'unique_together': {('user', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='FavouriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite Restaurant',
                'verbose_name_plural': 'Favourite Restaurants',
                'db_table': 'user_favourite_restaurants',
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
