# Generated by Django 5.2.11 on 2026-02-10 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_order_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(max_length=128)),
                ('otp_type', models.CharField(choices=[('PICKUP', 'Pickup Verification'), ('DELIVERY', 'Delivery Verification')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_otps', to='client.order')),
                ('related_user', models.ForeignKey(blank=True, help_text='User who verifies this OTP (e.g. Rider)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order OTP',
                'verbose_name_plural': 'Order OTPs',
                'db_table': 'order_otps',
                'indexes': [models.Index(fields=['order', 'otp_type', 'is_used'], name='order_otps_order_i_fbb6b7_idx'), models.Index(fields=['created_at'], name='order_otps_created_00129d_idx')],
            },
        ),
    ]
