# Generated by Django 5.2.11 on 2026-02-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_orderotp'),
        ('core', '0007_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.city'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='core.city'),
        ),
    ]
