# Generated by Django 5.2.11 on 2026-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_order_city_id_restaurant_city_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_status_2ce9fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_city_2eac77_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
