# Generated by Django 5.2.11 on 2026-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_remove_restaurant_restaurants_status_2ce9fb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
