# Generated by Django 5.2.11 on 2026-02-21 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_add_image_url_to_menuitem'),
        ('core', '0008_alter_otp_options_remove_otp_otps_phone_34bb78_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favouritemenuitem',
            index=models.Index(fields=['user'], name='idx_fav_item_user'),
        ),
        migrations.AddIndex(
            model_name='favouritemenuitem',
            index=models.Index(fields=['user', 'menu_item'], name='idx_fav_item_user_menuitem'),
        ),
        migrations.AddIndex(
            model_name='favouriterestaurant',
            index=models.Index(fields=['user'], name='idx_fav_rest_user'),
        ),
        migrations.AddIndex(
            model_name='favouriterestaurant',
            index=models.Index(fields=['user', 'restaurant'], name='idx_fav_rest_user_restaurant'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status', 'is_active'], name='idx_restaurant_status_active'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city'], name='idx_restaurant_city'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_restaurant_coordinates'),
        ),
    ]
