# Generated by Django 5.2.11 on 2026-02-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_favouritemenuitem_idx_fav_item_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g., from Pexels)', max_length=500, null=True),
        ),
    ]
