# Generated by Django 5.2.11 on 2026-02-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_restaurant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
    ]
