# Generated by Django 5.2.11 on 2026-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_remove_menuitem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
