# Generated by Django 5.2.11 on 2026-02-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='otps_phone_34bb78_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('PIN_RESET', 'Pin Reset')], default='LOGIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(db_index=True, max_length=17),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'otp_code', 'is_verified', 'is_used'], name='otps_phone_06deb6_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'otp_code', 'is_verified', 'is_used'], name='otps_email_d9b938_idx'),
        ),
    ]
