# Generated by Django 5.2.11 on 2026-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='payout_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payout',
            name='payout_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CARD', 'Card')], default='UPI', max_length=20),
        ),
    ]
