# Generated by Django 5.2.11 on 2026-02-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='city',
            field=models.CharField(default='Mehsana', max_length=100),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
