# Generated by Django 5.2.11 on 2026-02-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_rider_city_rider_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy')], default='OFFLINE', max_length=10),
        ),
    ]
