# Generated by Django 5.2.11 on 2026-02-27 18:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scheme_type', models.CharField(choices=[('DAILY_ORDER_TARGET', 'Daily Order Target'), ('PEAK_HOUR_BONUS', 'Peak Hour Bonus'), ('REFERRAL', 'Referral Bonus')], max_length=50)),
                ('target_count', models.IntegerField(help_text='Target number of orders')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, help_text='For peak hour bonuses', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='For peak hour bonuses', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rider_incentive_schemes',
            },
        ),
        migrations.CreateModel(
            name='RiderBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Bank Detail',
                'verbose_name_plural': 'Rider Bank Details',
                'db_table': 'rider_bank_details',
            },
        ),
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAR_FRONT', 'Aadhaar Card Front'), ('AADHAR_BACK', 'Aadhaar Card Back'), ('LICENSE', 'Driving License'), ('SELFIE_WITH_VEHICLE', 'Selfie with Vehicle')], max_length=50)),
                ('file', models.ImageField(upload_to='rider_documents/')),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Document',
                'verbose_name_plural': 'Rider Documents',
                'db_table': 'rider_documents',
            },
        ),
        migrations.CreateModel(
            name='RiderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ORDER', 'New Order Alert'), ('INCENTIVE', 'Incentive Milestone'), ('SYSTEM', 'System Message'), ('PAYOUT', 'Payment/Wallet Update')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='rider_profiles/')),
                ('city', models.CharField(default='Himmatnagar', max_length=100)),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('CYCLE', 'Cycle')], default='BIKE', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New Registration'), ('ONBOARDING', 'Onboarding in Progress'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20)),
                ('onboarding_step', models.IntegerField(default=0)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_profiles', to='core.city')),
                ('current_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rider_profile', to='client.order')),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Profile',
                'verbose_name_plural': 'Rider Profiles',
                'db_table': 'rider_profiles',
            },
        ),
        migrations.CreateModel(
            name='RiderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_review', to='client.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Review',
                'verbose_name_plural': 'Rider Reviews',
                'db_table': 'rider_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_earnings', to='client.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Earning',
                'verbose_name_plural': 'Rider Earnings',
                'db_table': 'rider_earnings',
                'indexes': [models.Index(fields=['rider', 'date'], name='rider_earni_rider_i_ca3ec5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderIncentiveProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_progress', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_legacy.incentivescheme')),
            ],
            options={
                'db_table': 'rider_incentive_progress',
                'unique_together': {('rider', 'scheme', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Location',
                'verbose_name_plural': 'Rider Locations',
                'db_table': 'rider_locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rider', '-timestamp'], name='rider_locat_rider_i_d148ed_idx')],
            },
        ),
    ]
