# Generated by Django 5.2.11 on 2026-03-04 16:52
# Modified: use RunSQL with IF NOT EXISTS to avoid duplicate column error
# on databases (Neon/PostgreSQL) where this column was already added manually.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name='rider_profiles' AND column_name='mobile_number'
                    ) THEN
                        ALTER TABLE rider_profiles
                        ADD COLUMN mobile_number varchar(15) NULL UNIQUE;
                    END IF;
                END$$;
            """,
            reverse_sql="""
                ALTER TABLE rider_profiles DROP COLUMN IF EXISTS mobile_number;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='riderprofile',
                    name='mobile_number',
                    field=models.CharField(blank=True, help_text='Single Source of Truth', max_length=15, null=True, unique=True),
                ),
            ],
        ),
    ]
