# Generated by Django 5.2.11 on 2026-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Single Source of Truth', max_length=15, null=True, unique=True),
        ),
    ]
