# Generated by Django 4.2.27 on 2025-12-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
