# Generated by Django 4.2.27 on 2025-12-30 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_order_delivery_otp_order_pickup_otp'),
        ('rider_legacy', '0002_riderprofile_aadhar_number_riderprofile_pan_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_review', to='client.order')),
                ('rider_legacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Review',
                'verbose_name_plural': 'Rider Reviews',
                'db_table': 'rider_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
