# Generated by Django 4.2.27 on 2026-01-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0003_riderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='password_plain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
