# Generated by Django 5.2.11 on 2026-02-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0004_riderprofile_password_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='city',
            field=models.CharField(default='Himmatnagar', max_length=100),
        ),
    ]
