# Generated by Django 5.2.11 on 2026-02-05 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0005_riderprofile_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rider_profiles/'),
        ),
        migrations.CreateModel(
            name='RiderBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider_legacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Bank Detail',
                'verbose_name_plural': 'Rider Bank Details',
                'db_table': 'rider_bank_details',
            },
        ),
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAR_FRONT', 'Aadhaar Card Front'), ('AADHAR_BACK', 'Aadhaar Card Back'), ('LICENSE', 'Driving License'), ('SELFIE_WITH_VEHICLE', 'Selfie with Vehicle')], max_length=50)),
                ('file', models.ImageField(upload_to='rider_documents/')),
                ('verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rider_legacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Document',
                'verbose_name_plural': 'Rider Documents',
                'db_table': 'rider_documents',
            },
        ),
    ]
