# Generated by Django 5.2.11 on 2026-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0006_riderprofile_profile_photo_riderbank_riderdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='onboarding_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Registration'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20),
        ),
    ]
