# Generated by Django 5.2.11 on 2026-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0007_riderprofile_is_onboarding_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Registration'), ('ONBOARDING', 'Onboarding in Progress'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20),
        ),
    ]
