# Generated by Django 5.2.11 on 2026-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0008_riderprofile_mobile_number_alter_riderprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
