# Generated by Django 5.2.11 on 2026-02-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_order_cancellation_reason'),
        ('rider_legacy', '0009_alter_riderprofile_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='password_plain',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rider_profile', to='client.order'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Single Source of Truth', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
