# Generated by Django 5.2.11 on 2026-02-09 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_legacy', '0010_remove_riderprofile_password_plain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scheme_type', models.CharField(choices=[('DAILY_ORDER_TARGET', 'Daily Order Target'), ('PEAK_HOUR_BONUS', 'Peak Hour Bonus'), ('REFERRAL', 'Referral Bonus')], max_length=50)),
                ('target_count', models.IntegerField(help_text='Target number of orders')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, help_text='For peak hour bonuses', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='For peak hour bonuses', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rider_incentive_schemes',
            },
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Registration'), ('ONBOARDING', 'Onboarding in Progress'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='RiderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ORDER', 'New Order Alert'), ('INCENTIVE', 'Incentive Milestone'), ('SYSTEM', 'System Message'), ('PAYOUT', 'Payment/Wallet Update')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider_legacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderIncentiveProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('rider_legacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_progress', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_legacy.incentivescheme')),
            ],
            options={
                'db_table': 'rider_incentive_progress',
                'unique_together': {('rider_legacy', 'scheme', 'date')},
            },
        ),
    ]
