# Generated by Django 5.2.11 on 2026-02-10 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_order_cancellation_reason'),
        ('rider_legacy', '0011_incentivescheme_alter_riderprofile_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='riderearnings',
            name='rider_earni_rider_i_ca3ec5_idx',
        ),
        migrations.RemoveIndex(
            model_name='riderlocation',
            name='rider_locat_rider_i_d148ed_idx',
        ),
        migrations.RenameField(
            model_name='riderbank',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='riderdocument',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='riderearnings',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='riderincentiveprogress',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='riderlocation',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='ridernotification',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='riderprofile',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.RenameField(
            model_name='riderreview',
            old_name='rider_legacy',
            new_name='rider',
        ),
        migrations.AlterUniqueTogether(
            name='riderincentiveprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='riderincentiveprogress',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider_legacy.incentivescheme'),
        ),
        migrations.AlterUniqueTogether(
            name='riderincentiveprogress',
            unique_together={('rider', 'scheme', 'date')},
        ),
        migrations.AddIndex(
            model_name='riderearnings',
            index=models.Index(fields=['rider', 'date'], name='rider_earni_rider_i_ca3ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='riderlocation',
            index=models.Index(fields=['rider', '-timestamp'], name='rider_locat_rider_i_d148ed_idx'),
        ),
    ]
