# Generated by Django 5.2.11 on 2026-02-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_city'),
        ('rider_legacy', '0012_remove_riderearnings_rider_earni_rider_i_ca3ec5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_profiles', to='core.city'),
        ),
    ]
