# Generated by Django 5.2.11 on 2026-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
