# -*- coding: utf-8 -*-
"""
All restaurants and dishes data for Foodis - specific names, prices, veg type.
Format: list of {"name", "location", "dishes": [{"name", "type", "price"}, ...]}
"""

RESTAURANTS_DATA = [
    {
        "name": "Biryani Boulevard",
        "location": "Mehsana",
        "dishes": [
            {"name": "Double Ka Meetha", "type": "VEG", "price": "80.00"},
            {"name": "Egg Biryani", "type": "NON_VEG", "price": "180.00"},
            {"name": "Fish Biryani", "type": "NON_VEG", "price": "320.00"},
            {"name": "Hyderabadi Chicken Dum Biryani", "type": "NON_VEG", "price": "280.00"},
            {"name": "Kolkata Biryani", "type": "NON_VEG", "price": "260.00"},
            {"name": "Mutton Biryani", "type": "NON_VEG", "price": "350.00"},
            {"name": "Paneer Biryani", "type": "VEG", "price": "200.00"},
            {"name": "Prawns Biryani", "type": "NON_VEG", "price": "380.00"},
            {"name": "Raita", "type": "VEG", "price": "50.00"},
            {"name": "Veg Biryani", "type": "VEG", "price": "160.00"},
        ],
    },
    {
        "name": "Biryani House",
        "location": "Mehsana",
        "dishes": [
            {"name": "Bagara Baingan", "type": "VEG", "price": "180.00"},
            {"name": "Boneless Chicken Biryani", "type": "NON_VEG", "price": "290.00"},
            {"name": "Chicken Biryani", "type": "NON_VEG", "price": "250.00"},
            {"name": "Dum Ka Murgh", "type": "NON_VEG", "price": "320.00"},
            {"name": "Family Pack Biryani", "type": "NON_VEG", "price": "850.00"},
            {"name": "Gulab Jamun (2 pcs)", "type": "VEG", "price": "60.00"},
            {"name": "Keema Biryani", "type": "NON_VEG", "price": "280.00"},
            {"name": "Lucknowi Biryani", "type": "NON_VEG", "price": "300.00"},
            {"name": "Mirchi Ka Salan", "type": "VEG", "price": "120.00"},
        ],
    },
    {
        "name": "Bombay Brasserie",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Bhel Puri", "type": "VEG", "price": "60.00"},
            {"name": "Bun Maska", "type": "VEG", "price": "50.00"},
            {"name": "Dabeli", "type": "VEG", "price": "50.00"},
            {"name": "Kanda Poha", "type": "VEG", "price": "60.00"},
            {"name": "Keema Pav", "type": "NON_VEG", "price": "180.00"},
            {"name": "Misal Pav", "type": "VEG", "price": "110.00"},
            {"name": "Pav Bhaji", "type": "VEG", "price": "120.00"},
            {"name": "Ragda Pattice", "type": "VEG", "price": "90.00"},
            {"name": "Sabudana Vada", "type": "VEG", "price": "80.00"},
            {"name": "Sev Puri", "type": "VEG", "price": "70.00"},
            {"name": "Vada Pav", "type": "VEG", "price": "45.00"},
        ],
    },
    {
        "name": "Bombay Sandwich Co",
        "location": "Mehsana",
        "dishes": [
            {"name": "Bombay Veg Sandwich", "type": "VEG", "price": "85.00"},
            {"name": "Chicken Mayo Sandwich", "type": "NON_VEG", "price": "160.00"},
            {"name": "Chilli Cheese Toast", "type": "VEG", "price": "120.00"},
            {"name": "Chocolate Toast", "type": "VEG", "price": "90.00"},
            {"name": "Club Sandwich", "type": "VEG", "price": "140.00"},
            {"name": "Corn Spinach Sandwich", "type": "VEG", "price": "120.00"},
            {"name": "Grilled Cheese Sandwich", "type": "VEG", "price": "110.00"},
            {"name": "Masala Toast", "type": "VEG", "price": "90.00"},
            {"name": "Paneer Tikka Sandwich", "type": "VEG", "price": "130.00"},
            {"name": "Pizza Sandwich", "type": "VEG", "price": "130.00"},
        ],
    },
    {
        "name": "Butter Chicken Co",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Butter Chicken Biryani", "type": "NON_VEG", "price": "320.00"},
            {"name": "Butter Chicken Roll", "type": "NON_VEG", "price": "180.00"},
            {"name": "Butter Garlic Naan", "type": "VEG", "price": "70.00"},
            {"name": "Butter Naan", "type": "VEG", "price": "60.00"},
            {"name": "Butter Paneer", "type": "VEG", "price": "280.00"},
            {"name": "Dal Butter Fry", "type": "VEG", "price": "200.00"},
            {"name": "Makhani Gravy Bowl", "type": "VEG", "price": "80.00"},
            {"name": "Signature Butter Chicken", "type": "NON_VEG", "price": "350.00"},
        ],
    },
    {
        "name": "Chaat Corner Premium",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Aloo Tikki Chaat", "type": "VEG", "price": "90.00"},
            {"name": "Basket Chaat", "type": "VEG", "price": "120.00"},
            {"name": "Dahi Puri", "type": "VEG", "price": "80.00"},
            {"name": "Dahi Vada", "type": "VEG", "price": "90.00"},
            {"name": "Palak Patta Chaat", "type": "VEG", "price": "100.00"},
            {"name": "Pani Puri (6 pcs)", "type": "VEG", "price": "60.00"},
            {"name": "Papdi Chaat", "type": "VEG", "price": "80.00"},
            {"name": "Raj Kachori", "type": "VEG", "price": "110.00"},
            {"name": "Samosa Chaat", "type": "VEG", "price": "90.00"},
            {"name": "Sev Puri", "type": "VEG", "price": "70.00"},
        ],
    },
    {
        "name": "Charcoal Grill",
        "location": "Mehsana",
        "dishes": [
            {"name": "Butter Naan", "type": "VEG", "price": "50.00"},
            {"name": "Chicken Malai Tikka", "type": "NON_VEG", "price": "360.00"},
            {"name": "Chicken Tikka", "type": "NON_VEG", "price": "340.00"},
            {"name": "Fish Tikka", "type": "NON_VEG", "price": "380.00"},
            {"name": "Garlic Naan", "type": "VEG", "price": "60.00"},
            {"name": "Laccha Paratha", "type": "VEG", "price": "70.00"},
            {"name": "Mutton Seekh Kebab", "type": "NON_VEG", "price": "380.00"},
            {"name": "Paneer Tikka", "type": "VEG", "price": "280.00"},
            {"name": "Reshmi Kebab", "type": "NON_VEG", "price": "330.00"},
            {"name": "Seekh Kebab", "type": "NON_VEG", "price": "340.00"},
            {"name": "Tandoori Chicken Full", "type": "NON_VEG", "price": "680.00"},
            {"name": "Tandoori Chicken Half", "type": "NON_VEG", "price": "380.00"},
            {"name": "Tandoori Mushroom", "type": "VEG", "price": "260.00"},
            {"name": "Tandoori Prawns", "type": "NON_VEG", "price": "480.00"},
            {"name": "Tandoori Roti", "type": "VEG", "price": "30.00"},
        ],
    },
    {
        "name": "Curry Craft",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Butter Chicken", "type": "NON_VEG", "price": "340.00"},
            {"name": "Butter Naan", "type": "VEG", "price": "50.00"},
            {"name": "Chicken Korma", "type": "NON_VEG", "price": "310.00"},
            {"name": "Dal Makhani", "type": "VEG", "price": "240.00"},
            {"name": "Dum Aloo Kashmiri", "type": "VEG", "price": "230.00"},
            {"name": "Garlic Naan", "type": "VEG", "price": "60.00"},
            {"name": "Jeera Rice", "type": "VEG", "price": "120.00"},
            {"name": "Kadhai Chicken", "type": "NON_VEG", "price": "320.00"},
            {"name": "Kadhai Paneer", "type": "VEG", "price": "260.00"},
            {"name": "Lahori Chicken", "type": "NON_VEG", "price": "340.00"},
            {"name": "Malai Kofta", "type": "VEG", "price": "270.00"},
            {"name": "Methi Chicken", "type": "NON_VEG", "price": "300.00"},
            {"name": "Mutton Rogan Josh", "type": "NON_VEG", "price": "420.00"},
            {"name": "Paneer Bhurji", "type": "VEG", "price": "240.00"},
            {"name": "Paneer Butter Masala", "type": "VEG", "price": "280.00"},
        ],
    },
    {
        "name": "Curry House Deluxe",
        "location": "Mehsana",
        "dishes": [
            {"name": "Bhuna Gosht", "type": "NON_VEG", "price": "440.00"},
            {"name": "Cheese Naan", "type": "VEG", "price": "90.00"},
            {"name": "Chicken Tikka Masala", "type": "NON_VEG", "price": "360.00"},
            {"name": "Dal Bukhara", "type": "VEG", "price": "260.00"},
            {"name": "Murgh Musallam", "type": "NON_VEG", "price": "750.00"},
            {"name": "Nalli Nihari", "type": "NON_VEG", "price": "480.00"},
            {"name": "Navratan Korma", "type": "VEG", "price": "260.00"},
            {"name": "Paneer Do Pyaza", "type": "VEG", "price": "270.00"},
            {"name": "Paneer Lababdar", "type": "VEG", "price": "280.00"},
            {"name": "Peshawari Naan", "type": "VEG", "price": "100.00"},
            {"name": "Premium Butter Chicken", "type": "NON_VEG", "price": "380.00"},
            {"name": "Shahi Paneer", "type": "VEG", "price": "290.00"},
            {"name": "Stuffed Kulcha", "type": "VEG", "price": "80.00"},
        ],
    },
    {
        "name": "Desi Delights",
        "location": "Mehsana",
        "dishes": [
            {"name": "Aloo Gobi", "type": "VEG", "price": "160.00"},
            {"name": "Baingan Bharta", "type": "VEG", "price": "180.00"},
            {"name": "Bhindi Masala", "type": "VEG", "price": "170.00"},
            {"name": "Butter Roti", "type": "VEG", "price": "30.00"},
            {"name": "Chole Masala", "type": "VEG", "price": "180.00"},
            {"name": "Dal Tadka", "type": "VEG", "price": "180.00"},
            {"name": "Jeera Aloo", "type": "VEG", "price": "130.00"},
            {"name": "Kadhi Pakora", "type": "VEG", "price": "160.00"},
            {"name": "Mix Veg Curry", "type": "VEG", "price": "170.00"},
            {"name": "Palak Paneer", "type": "VEG", "price": "240.00"},
            {"name": "Phulka", "type": "VEG", "price": "25.00"},
            {"name": "Rajma Masala", "type": "VEG", "price": "190.00"},
            {"name": "Steamed Rice", "type": "VEG", "price": "80.00"},
            {"name": "Tawa Roti", "type": "VEG", "price": "20.00"},
        ],
    },
    {
        "name": "Dosa Darbar",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Butter Dosa", "type": "VEG", "price": "90.00"},
            {"name": "Cheese Dosa", "type": "VEG", "price": "120.00"},
            {"name": "Ghee Roast Dosa", "type": "VEG", "price": "100.00"},
            {"name": "Mysore Masala Dosa", "type": "VEG", "price": "110.00"},
            {"name": "Paneer Dosa", "type": "VEG", "price": "130.00"},
            {"name": "Paper Dosa", "type": "VEG", "price": "95.00"},
            {"name": "Podi Dosa", "type": "VEG", "price": "85.00"},
            {"name": "Rava Masala Dosa", "type": "VEG", "price": "105.00"},
            {"name": "Set Dosa (3 pcs)", "type": "VEG", "price": "90.00"},
            {"name": "Spring Dosa", "type": "VEG", "price": "115.00"},
        ],
    },
    {
        "name": "Emperor Table",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Assorted Bread Basket", "type": "VEG", "price": "180.00"},
            {"name": "Chicken Wellington", "type": "NON_VEG", "price": "520.00"},
            {"name": "Chocolate Lava Cake", "type": "VEG", "price": "180.00"},
            {"name": "Exotic Vegetable Stir Fry", "type": "VEG", "price": "280.00"},
            {"name": "Grilled Fish Steak", "type": "NON_VEG", "price": "480.00"},
            {"name": "Murgh Makhani", "type": "NON_VEG", "price": "380.00"},
            {"name": "Mutton Galouti Kebab", "type": "NON_VEG", "price": "420.00"},
            {"name": "Paneer Tikka Masala", "type": "VEG", "price": "290.00"},
            {"name": "Prawn Thermidor", "type": "NON_VEG", "price": "550.00"},
            {"name": "Saffron Rice", "type": "VEG", "price": "150.00"},
            {"name": "Shahi Paneer", "type": "VEG", "price": "310.00"},
            {"name": "Truffle Mushroom Risotto", "type": "VEG", "price": "380.00"},
        ],
    },
    {
        "name": "Fusion Flames",
        "location": "Mehsana",
        "dishes": [
            {"name": "Burrito Bowl", "type": "VEG", "price": "260.00"},
            {"name": "Butter Chicken Pizza", "type": "NON_VEG", "price": "350.00"},
            {"name": "Chicken Tikka Tacos", "type": "NON_VEG", "price": "280.00"},
            {"name": "Gulab Jamun Cheesecake", "type": "VEG", "price": "180.00"},
            {"name": "Masala Pasta", "type": "VEG", "price": "220.00"},
            {"name": "Naan Pizza", "type": "VEG", "price": "240.00"},
            {"name": "Paneer Tikka Pizza", "type": "VEG", "price": "300.00"},
            {"name": "Pav Bhaji Fondue", "type": "VEG", "price": "320.00"},
            {"name": "Schezwan Dosa", "type": "VEG", "price": "160.00"},
            {"name": "Tandoori Momos", "type": "VEG", "price": "200.00"},
        ],
    },
    {
        "name": "Golden Fork",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Butter Chicken", "type": "NON_VEG", "price": "320.00"},
            {"name": "Chicken Biryani", "type": "NON_VEG", "price": "280.00"},
            {"name": "Chicken Fried Rice", "type": "NON_VEG", "price": "190.00"},
            {"name": "Chicken Manchurian", "type": "NON_VEG", "price": "280.00"},
            {"name": "Dal Makhani", "type": "VEG", "price": "220.00"},
            {"name": "Fish Fingers", "type": "NON_VEG", "price": "260.00"},
            {"name": "French Fries", "type": "VEG", "price": "90.00"},
            {"name": "Garlic Bread", "type": "VEG", "price": "120.00"},
            {"name": "Garlic Naan", "type": "VEG", "price": "60.00"},
            {"name": "Hakka Noodles", "type": "VEG", "price": "160.00"},
            {"name": "Mixed Sauce Pasta", "type": "VEG", "price": "220.00"},
            {"name": "Paneer Tikka Masala", "type": "VEG", "price": "270.00"},
            {"name": "Veg Fried Rice", "type": "VEG", "price": "150.00"},
            {"name": "Veg Manchurian", "type": "VEG", "price": "180.00"},
        ],
    },
    {
        "name": "Idli Sambar Express",
        "location": "Mehsana",
        "dishes": [
            {"name": "Coconut Chutney", "type": "VEG", "price": "20.00"},
            {"name": "Curd Rice", "type": "VEG", "price": "75.00"},
            {"name": "Filter Coffee", "type": "VEG", "price": "40.00"},
            {"name": "Idli (3 pcs)", "type": "VEG", "price": "60.00"},
            {"name": "Masala Dosa", "type": "VEG", "price": "90.00"},
            {"name": "Medu Vada (2 pcs)", "type": "VEG", "price": "70.00"},
            {"name": "Onion Uttapam", "type": "VEG", "price": "80.00"},
            {"name": "Plain Dosa", "type": "VEG", "price": "70.00"},
            {"name": "Rava Dosa", "type": "VEG", "price": "85.00"},
            {"name": "Sambar Rice", "type": "VEG", "price": "95.00"},
        ],
    },
    {
        "name": "Kebab Factory",
        "location": "Mehsana",
        "dishes": [
            {"name": "Chicken Malai Tikka", "type": "NON_VEG", "price": "340.00"},
            {"name": "Galouti Kebab", "type": "NON_VEG", "price": "380.00"},
            {"name": "Kakori Kebab", "type": "NON_VEG", "price": "360.00"},
            {"name": "Kebab Platter", "type": "NON_VEG", "price": "650.00"},
            {"name": "Mutton Burra", "type": "NON_VEG", "price": "420.00"},
            {"name": "Reshmi Kebab", "type": "NON_VEG", "price": "330.00"},
            {"name": "Shami Kebab", "type": "NON_VEG", "price": "320.00"},
            {"name": "Veg Seekh Kebab", "type": "VEG", "price": "240.00"},
        ],
    },
    {
        "name": "Masala Magic",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "American Chopsuey", "type": "VEG", "price": "210.00"},
            {"name": "Chilli Paneer", "type": "VEG", "price": "250.00"},
            {"name": "Chinese Bhel", "type": "VEG", "price": "140.00"},
            {"name": "Gobi Manchurian", "type": "VEG", "price": "180.00"},
            {"name": "Manchow Soup", "type": "VEG", "price": "120.00"},
            {"name": "Schezwan Fried Rice", "type": "VEG", "price": "180.00"},
            {"name": "Spring Rolls", "type": "VEG", "price": "160.00"},
            {"name": "Triple Schezwan Rice", "type": "VEG", "price": "240.00"},
            {"name": "Veg Hakka Noodles", "type": "VEG", "price": "170.00"},
            {"name": "Veg Manchurian Dry", "type": "VEG", "price": "190.00"},
        ],
    },
    {
        "name": "Moksha Dining",
        "location": "Mehsana",
        "dishes": [
            {"name": "Assorted Naan Basket", "type": "VEG", "price": "160.00"},
            {"name": "Bharwan Shimla Mirch", "type": "VEG", "price": "270.00"},
            {"name": "Dal Makhani", "type": "VEG", "price": "250.00"},
            {"name": "Dum Aloo Banarasi", "type": "VEG", "price": "260.00"},
            {"name": "Gulab Jamun", "type": "VEG", "price": "80.00"},
            {"name": "Hara Bhara Kebab", "type": "VEG", "price": "240.00"},
            {"name": "Jeera Pulao", "type": "VEG", "price": "140.00"},
            {"name": "Malai Kofta", "type": "VEG", "price": "280.00"},
            {"name": "Mushroom Masala", "type": "VEG", "price": "260.00"},
            {"name": "Paneer Lababdar", "type": "VEG", "price": "290.00"},
            {"name": "Paneer Tikka Achari", "type": "VEG", "price": "310.00"},
            {"name": "Subz Seekh Kebab", "type": "VEG", "price": "260.00"},
            {"name": "Veg Biryani", "type": "VEG", "price": "240.00"},
        ],
    },
    {
        "name": "Momo Mania Deluxe",
        "location": "Mehsana",
        "dishes": [
            {"name": "Cheese Corn Momos (8 pcs)", "type": "VEG", "price": "170.00"},
            {"name": "Chicken Thukpa", "type": "NON_VEG", "price": "180.00"},
            {"name": "Chocolate Momos (4 pcs)", "type": "VEG", "price": "140.00"},
            {"name": "Fried Chicken Momos (8 pcs)", "type": "NON_VEG", "price": "180.00"},
            {"name": "Kurkure Momos", "type": "VEG", "price": "180.00"},
            {"name": "Momo Platter (12 pcs)", "type": "VEG", "price": "280.00"},
            {"name": "Paneer Momos (8 pcs)", "type": "VEG", "price": "150.00"},
            {"name": "Schezwan Momos (8 pcs)", "type": "VEG", "price": "160.00"},
            {"name": "Steamed Veg Momos (8 pcs)", "type": "VEG", "price": "120.00"},
            {"name": "Tandoori Momos (8 pcs)", "type": "VEG", "price": "190.00"},
        ],
    },
    {
        "name": "Nawab Delight",
        "location": "Mehsana",
        "dishes": [
            {"name": "Butter Naan", "type": "VEG", "price": "50.00"},
            {"name": "Chicken Biryani", "type": "NON_VEG", "price": "300.00"},
            {"name": "Chicken Changezi", "type": "NON_VEG", "price": "340.00"},
            {"name": "Chicken Mughlai", "type": "NON_VEG", "price": "350.00"},
            {"name": "Chicken Seekh Kebab", "type": "NON_VEG", "price": "330.00"},
            {"name": "Kakori Kebab", "type": "NON_VEG", "price": "380.00"},
            {"name": "Laccha Paratha", "type": "VEG", "price": "70.00"},
            {"name": "Mutton Biryani", "type": "NON_VEG", "price": "380.00"},
            {"name": "Mutton Galouti Kebab", "type": "NON_VEG", "price": "400.00"},
            {"name": "Mutton Korma", "type": "NON_VEG", "price": "420.00"},
            {"name": "Rumali Roti", "type": "VEG", "price": "40.00"},
            {"name": "Shahi Tukda", "type": "VEG", "price": "120.00"},
        ],
    },
    {
        "name": "Paneer Paradise",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Kadhai Paneer", "type": "VEG", "price": "250.00"},
            {"name": "Malai Paneer", "type": "VEG", "price": "270.00"},
            {"name": "Palak Paneer", "type": "VEG", "price": "240.00"},
            {"name": "Paneer Bhurji", "type": "VEG", "price": "230.00"},
            {"name": "Paneer Butter Masala", "type": "VEG", "price": "270.00"},
            {"name": "Paneer Do Pyaza", "type": "VEG", "price": "250.00"},
            {"name": "Paneer Lababdar", "type": "VEG", "price": "260.00"},
            {"name": "Paneer Tikka Masala", "type": "VEG", "price": "260.00"},
            {"name": "Shahi Paneer", "type": "VEG", "price": "280.00"},
        ],
    },
    {
        "name": "Royal Kathiyawadi",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Bajra Rotla with Ghee", "type": "VEG", "price": "80.00"},
            {"name": "Bajri No Rotlo", "type": "VEG", "price": "40.00"},
            {"name": "Buttermilk", "type": "VEG", "price": "40.00"},
            {"name": "Kachariyu", "type": "VEG", "price": "90.00"},
            {"name": "Kathiyawadi Kadhi", "type": "VEG", "price": "160.00"},
            {"name": "Kathiyawadi Thali", "type": "VEG", "price": "320.00"},
            {"name": "Lasaniya Batata", "type": "VEG", "price": "150.00"},
            {"name": "Mag Ni Dal", "type": "VEG", "price": "130.00"},
            {"name": "Ringna Olo", "type": "VEG", "price": "170.00"},
            {"name": "Sev Tameta", "type": "VEG", "price": "140.00"},
        ],
    },
    {
        "name": "Royal Rajdhani",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Aamras (Seasonal)", "type": "VEG", "price": "150.00"},
            {"name": "Dal Baati Churma", "type": "VEG", "price": "240.00"},
            {"name": "Dhokla", "type": "VEG", "price": "80.00"},
            {"name": "Farsan Platter", "type": "VEG", "price": "140.00"},
            {"name": "Gatte Ki Sabzi", "type": "VEG", "price": "180.00"},
            {"name": "Gujarati Thali", "type": "VEG", "price": "320.00"},
            {"name": "Kadhi Khichdi", "type": "VEG", "price": "160.00"},
            {"name": "Mohanthal", "type": "VEG", "price": "100.00"},
            {"name": "Rajasthani Thali", "type": "VEG", "price": "350.00"},
            {"name": "Undhiyu", "type": "VEG", "price": "200.00"},
        ],
    },
    {
        "name": "Royal Rasoi",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Butter Naan", "type": "VEG", "price": "55.00"},
            {"name": "Chicken Korma", "type": "NON_VEG", "price": "330.00"},
            {"name": "Gajar Ka Halwa", "type": "VEG", "price": "100.00"},
            {"name": "Jeera Rice", "type": "VEG", "price": "130.00"},
            {"name": "Kadhai Chicken", "type": "NON_VEG", "price": "340.00"},
            {"name": "Malai Kofta", "type": "VEG", "price": "280.00"},
            {"name": "Palak Paneer", "type": "VEG", "price": "260.00"},
            {"name": "Raita", "type": "VEG", "price": "60.00"},
            {"name": "Tandoori Roti", "type": "VEG", "price": "35.00"},
        ],
    },
    {
        "name": "Saffron Lounge",
        "location": "Mehsana",
        "dishes": [
            {"name": "Butter Naan", "type": "VEG", "price": "55.00"},
            {"name": "Chicken Tikka Premium", "type": "NON_VEG", "price": "380.00"},
            {"name": "Dal Makhani Lounge Special", "type": "VEG", "price": "280.00"},
            {"name": "Kesar Paneer", "type": "VEG", "price": "320.00"},
            {"name": "Kulfi Falooda", "type": "VEG", "price": "140.00"},
            {"name": "Malai Broccoli", "type": "VEG", "price": "280.00"},
            {"name": "Paneer Tikka Saffron", "type": "VEG", "price": "340.00"},
            {"name": "Saffron Chicken", "type": "NON_VEG", "price": "400.00"},
            {"name": "Stuffed Tandoori Pomfret", "type": "NON_VEG", "price": "580.00"},
            {"name": "Zaffrani Pulao", "type": "VEG", "price": "180.00"},
        ],
    },
    {
        "name": "Seafood Sensation",
        "location": "Mehsana",
        "dishes": [
            {"name": "Butter Garlic Prawns", "type": "NON_VEG", "price": "420.00"},
            {"name": "Crab Roast", "type": "NON_VEG", "price": "520.00"},
            {"name": "Goan Fish Curry", "type": "NON_VEG", "price": "340.00"},
            {"name": "Pomfret Fry", "type": "NON_VEG", "price": "480.00"},
            {"name": "Rawas Masala", "type": "NON_VEG", "price": "380.00"},
            {"name": "Seafood Platter", "type": "NON_VEG", "price": "680.00"},
            {"name": "Surmai Tikka", "type": "NON_VEG", "price": "420.00"},
        ],
    },
    {
        "name": "Sizzler Palace",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Brownie Sizzler", "type": "VEG", "price": "220.00"},
            {"name": "Chicken Satellite Sizzler", "type": "NON_VEG", "price": "450.00"},
            {"name": "Chinese Sizzler", "type": "VEG", "price": "360.00"},
            {"name": "Grilled Fish Sizzler", "type": "NON_VEG", "price": "480.00"},
            {"name": "Mixed Grill Sizzler", "type": "NON_VEG", "price": "580.00"},
            {"name": "Paneer Tikka Sizzler", "type": "VEG", "price": "380.00"},
            {"name": "Prawns Sizzler", "type": "NON_VEG", "price": "520.00"},
            {"name": "Veg Sizzler", "type": "VEG", "price": "340.00"},
        ],
    },
    {
        "name": "Spice Garden",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Basil Paneer Tikka", "type": "VEG", "price": "290.00"},
            {"name": "Farm Fresh Vegetable Bowl", "type": "VEG", "price": "240.00"},
            {"name": "Fresh Fruit Salad", "type": "VEG", "price": "120.00"},
            {"name": "Garden Fresh Salad", "type": "VEG", "price": "150.00"},
            {"name": "Garden Pasta", "type": "VEG", "price": "260.00"},
            {"name": "Herb Grilled Chicken", "type": "NON_VEG", "price": "360.00"},
            {"name": "Herb Quinoa Bowl", "type": "VEG", "price": "280.00"},
            {"name": "Herbed Cottage Cheese Steak", "type": "VEG", "price": "310.00"},
            {"name": "Herbed Focaccia", "type": "VEG", "price": "100.00"},
            {"name": "Mint Coriander Chicken", "type": "NON_VEG", "price": "340.00"},
            {"name": "Rosemary Mushroom", "type": "VEG", "price": "270.00"},
            {"name": "Thyme Roasted Vegetables", "type": "VEG", "price": "230.00"},
        ],
    },
    {
        "name": "Spice Symphony",
        "location": "Mehsana",
        "dishes": [
            {"name": "Appam (2 pcs)", "type": "VEG", "price": "80.00"},
            {"name": "Bengali Fish Curry", "type": "NON_VEG", "price": "340.00"},
            {"name": "Butter Naan", "type": "VEG", "price": "50.00"},
            {"name": "Chettinad Chicken", "type": "NON_VEG", "price": "350.00"},
            {"name": "Chettinad Veg Curry", "type": "VEG", "price": "240.00"},
            {"name": "Dal Tadka", "type": "VEG", "price": "190.00"},
            {"name": "Goan Fish Curry", "type": "NON_VEG", "price": "360.00"},
            {"name": "Hyderabadi Chicken Curry", "type": "NON_VEG", "price": "340.00"},
            {"name": "Kolhapuri Mutton", "type": "NON_VEG", "price": "430.00"},
            {"name": "Paneer Tikka Masala", "type": "VEG", "price": "280.00"},
            {"name": "Punjabi Chicken Curry", "type": "NON_VEG", "price": "320.00"},
            {"name": "Rajasthani Laal Maas", "type": "NON_VEG", "price": "450.00"},
            {"name": "Steamed Rice", "type": "VEG", "price": "80.00"},
        ],
    },
    {
        "name": "Spicy Affairs",
        "location": "Mehsana",
        "dishes": [
            {"name": "Andhra Chicken Curry", "type": "NON_VEG", "price": "340.00"},
            {"name": "Butter Naan", "type": "VEG", "price": "50.00"},
            {"name": "Chettinad Fish Curry", "type": "NON_VEG", "price": "360.00"},
            {"name": "Chilli Paneer Extreme", "type": "VEG", "price": "270.00"},
            {"name": "Ghost Pepper Chicken", "type": "NON_VEG", "price": "380.00"},
            {"name": "Jeera Rice", "type": "VEG", "price": "120.00"},
            {"name": "Kolhapuri Mutton", "type": "NON_VEG", "price": "450.00"},
            {"name": "Kolhapuri Veg", "type": "VEG", "price": "230.00"},
            {"name": "Mirchi Ka Salan", "type": "VEG", "price": "200.00"},
            {"name": "Schezwan Paneer", "type": "VEG", "price": "260.00"},
            {"name": "Spicy Paneer Tikka", "type": "VEG", "price": "280.00"},
            {"name": "Vindaloo Chicken", "type": "NON_VEG", "price": "350.00"},
        ],
    },
    {
        "name": "Taj Palace",
        "location": "Mehsana",
        "dishes": [
            {"name": "Butter Chicken", "type": "NON_VEG", "price": "360.00"},
            {"name": "Chicken Seekh Kebab", "type": "NON_VEG", "price": "340.00"},
            {"name": "Dal Makhani", "type": "VEG", "price": "260.00"},
            {"name": "Gulab Jamun (2 pcs)", "type": "VEG", "price": "80.00"},
            {"name": "Naan Basket", "type": "VEG", "price": "160.00"},
            {"name": "Paneer Butter Masala", "type": "VEG", "price": "300.00"},
            {"name": "Paneer Tikka", "type": "VEG", "price": "300.00"},
            {"name": "Rogan Josh", "type": "NON_VEG", "price": "450.00"},
            {"name": "Shahi Tukda", "type": "VEG", "price": "130.00"},
            {"name": "Tandoori Murgh Full", "type": "NON_VEG", "price": "680.00"},
        ],
    },
    {
        "name": "Tandoor Treasures",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Afghani Chicken", "type": "NON_VEG", "price": "360.00"},
            {"name": "Chicken Tikka", "type": "NON_VEG", "price": "320.00"},
            {"name": "Fish Tikka", "type": "NON_VEG", "price": "380.00"},
            {"name": "Hara Bhara Kebab", "type": "VEG", "price": "220.00"},
            {"name": "Paneer Tikka", "type": "VEG", "price": "280.00"},
            {"name": "Seekh Kebab", "type": "NON_VEG", "price": "340.00"},
            {"name": "Tandoori Chicken Half", "type": "NON_VEG", "price": "350.00"},
            {"name": "Tandoori Mushroom", "type": "VEG", "price": "260.00"},
            {"name": "Tandoori Prawns", "type": "NON_VEG", "price": "480.00"},
        ],
    },
    {
        "name": "Test Res",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Brownie", "type": "VEG", "price": "150.00"},
            {"name": "Coke", "type": "VEG", "price": "50.00"},
            {"name": "Garlic Bread", "type": "VEG", "price": "100.00"},
            {"name": "Margherita Pizza", "type": "VEG", "price": "200.00"},
        ],
    },
    {
        "name": "Thali Treasures",
        "location": "Mehsana",
        "dishes": [
            {"name": "Dhokla", "type": "VEG", "price": "60.00"},
            {"name": "Gujarati Thali", "type": "VEG", "price": "280.00"},
            {"name": "Kathiyawadi Thali", "type": "VEG", "price": "300.00"},
            {"name": "Khandvi", "type": "VEG", "price": "80.00"},
            {"name": "Mini Thali", "type": "VEG", "price": "180.00"},
            {"name": "North Indian Thali", "type": "VEG", "price": "280.00"},
            {"name": "Rajasthani Thali", "type": "VEG", "price": "320.00"},
            {"name": "South Indian Thali", "type": "VEG", "price": "260.00"},
            {"name": "Undhiyu", "type": "VEG", "price": "160.00"},
        ],
    },
    {
        "name": "The Coastal Kitchen",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Crab Roast", "type": "NON_VEG", "price": "450.00"},
            {"name": "Fish Curry", "type": "NON_VEG", "price": "320.00"},
            {"name": "Fish Thali", "type": "NON_VEG", "price": "350.00"},
            {"name": "Fried Calamari", "type": "NON_VEG", "price": "320.00"},
            {"name": "Lobster Thermidor", "type": "NON_VEG", "price": "950.00"},
            {"name": "Neer Dosa", "type": "VEG", "price": "80.00"},
            {"name": "Prawn Masala", "type": "NON_VEG", "price": "380.00"},
            {"name": "Sol Kadhi", "type": "VEG", "price": "60.00"},
            {"name": "Steam Rice", "type": "VEG", "price": "80.00"},
            {"name": "Surmai Fry", "type": "NON_VEG", "price": "400.00"},
        ],
    },
    {
        "name": "The Coastal Spice",
        "location": "Mehsana",
        "dishes": [
            {"name": "Appam (2 pcs)", "type": "VEG", "price": "80.00"},
            {"name": "Avial", "type": "VEG", "price": "220.00"},
            {"name": "Chettinad Chicken", "type": "NON_VEG", "price": "340.00"},
            {"name": "Chicken Cafreal", "type": "NON_VEG", "price": "330.00"},
            {"name": "Kerala Parotta with Beef Fry", "type": "NON_VEG", "price": "320.00"},
            {"name": "Malabar Fish Curry", "type": "NON_VEG", "price": "360.00"},
            {"name": "Malabar Parotta", "type": "VEG", "price": "60.00"},
            {"name": "Mutton Stew", "type": "NON_VEG", "price": "380.00"},
            {"name": "Neer Dosa (3 pcs)", "type": "VEG", "price": "90.00"},
            {"name": "Prawn Ghee Roast", "type": "NON_VEG", "price": "420.00"},
            {"name": "Sol Kadhi", "type": "VEG", "price": "70.00"},
            {"name": "Vegetable Stew", "type": "VEG", "price": "240.00"},
        ],
    },
    {
        "name": "The Curry Club",
        "location": "Mehsana",
        "dishes": [
            {"name": "Butter Naan", "type": "VEG", "price": "50.00"},
            {"name": "Chicken Tikka Masala", "type": "NON_VEG", "price": "340.00"},
            {"name": "Club Special Butter Chicken", "type": "NON_VEG", "price": "360.00"},
            {"name": "Dal Makhani", "type": "VEG", "price": "240.00"},
            {"name": "Fish Curry Bengali Style", "type": "NON_VEG", "price": "350.00"},
            {"name": "Garlic Naan", "type": "VEG", "price": "60.00"},
            {"name": "Kadhai Paneer", "type": "VEG", "price": "270.00"},
            {"name": "Lamb Rogan Josh", "type": "NON_VEG", "price": "450.00"},
            {"name": "Malai Kofta", "type": "VEG", "price": "280.00"},
            {"name": "Mixed Veg Curry", "type": "VEG", "price": "220.00"},
            {"name": "Palak Paneer", "type": "VEG", "price": "260.00"},
            {"name": "Paneer Tikka Masala", "type": "VEG", "price": "280.00"},
            {"name": "Prawn Malai Curry", "type": "NON_VEG", "price": "420.00"},
        ],
    },
    {
        "name": "The Dhaba Deluxe",
        "location": "Mehsana",
        "dishes": [
            {"name": "Aloo Paratha", "type": "VEG", "price": "70.00"},
            {"name": "Amritsari Kulcha", "type": "VEG", "price": "80.00"},
            {"name": "Chole Bhature", "type": "VEG", "price": "140.00"},
            {"name": "Dal Tadka", "type": "VEG", "price": "180.00"},
            {"name": "Highway Chicken Curry", "type": "NON_VEG", "price": "280.00"},
            {"name": "Lassi (Sweet/Salted)", "type": "VEG", "price": "60.00"},
            {"name": "Makki Ki Roti", "type": "VEG", "price": "40.00"},
            {"name": "Mixed Veg", "type": "VEG", "price": "160.00"},
            {"name": "Sarson Ka Saag", "type": "VEG", "price": "200.00"},
        ],
    },
    {
        "name": "The Naan Stop",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Butter Naan", "type": "VEG", "price": "50.00"},
            {"name": "Cheese Naan", "type": "VEG", "price": "90.00"},
            {"name": "Garlic Naan", "type": "VEG", "price": "60.00"},
            {"name": "Keema Naan", "type": "NON_VEG", "price": "120.00"},
            {"name": "Lachha Paratha", "type": "VEG", "price": "70.00"},
            {"name": "Naan Basket (Assorted)", "type": "VEG", "price": "180.00"},
            {"name": "Peshawari Naan", "type": "VEG", "price": "100.00"},
            {"name": "Tandoori Roti", "type": "VEG", "price": "30.00"},
        ],
    },
    {
        "name": "The Paratha Place",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Aloo Paratha", "type": "VEG", "price": "70.00"},
            {"name": "Dal Paratha", "type": "VEG", "price": "75.00"},
            {"name": "Gobi Paratha", "type": "VEG", "price": "80.00"},
            {"name": "Mix Veg Paratha", "type": "VEG", "price": "90.00"},
            {"name": "Mooli Paratha", "type": "VEG", "price": "70.00"},
            {"name": "Onion Paratha", "type": "VEG", "price": "70.00"},
            {"name": "Paneer Paratha", "type": "VEG", "price": "90.00"},
            {"name": "Paratha Combo", "type": "VEG", "price": "160.00"},
        ],
    },
    {
        "name": "The Rajwada",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Bajre Ki Roti", "type": "VEG", "price": "35.00"},
            {"name": "Dal Baati Churma", "type": "VEG", "price": "280.00"},
            {"name": "Gatte Ki Sabzi", "type": "VEG", "price": "220.00"},
            {"name": "Ghevar", "type": "VEG", "price": "150.00"},
            {"name": "Jungli Maas", "type": "NON_VEG", "price": "490.00"},
            {"name": "Ker Sangri", "type": "VEG", "price": "240.00"},
            {"name": "Mawa Kachori", "type": "VEG", "price": "90.00"},
            {"name": "Mirchi Vada", "type": "VEG", "price": "120.00"},
            {"name": "Rajasthani Laal Maas", "type": "NON_VEG", "price": "480.00"},
            {"name": "Safed Maas", "type": "NON_VEG", "price": "460.00"},
        ],
    },
    {
        "name": "The Royal Platter",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Bread Basket Royal", "type": "VEG", "price": "180.00"},
            {"name": "Dessert Platter", "type": "VEG", "price": "280.00"},
            {"name": "Kebab Platter", "type": "NON_VEG", "price": "680.00"},
            {"name": "Paneer Platter", "type": "VEG", "price": "450.00"},
            {"name": "Royal Biryani Platter", "type": "NON_VEG", "price": "520.00"},
            {"name": "Royal Chicken Platter", "type": "NON_VEG", "price": "650.00"},
            {"name": "Royal Veg Platter", "type": "VEG", "price": "480.00"},
            {"name": "Seafood Royal Platter", "type": "NON_VEG", "price": "820.00"},
            {"name": "Tandoori Platter", "type": "NON_VEG", "price": "720.00"},
            {"name": "Thali Special", "type": "VEG", "price": "380.00"},
        ],
    },
    {
        "name": "The Spice Route",
        "location": "Mehsana",
        "dishes": [
            {"name": "Appam (3 pcs)", "type": "VEG", "price": "90.00"},
            {"name": "Awadhi Chicken Korma", "type": "NON_VEG", "price": "360.00"},
            {"name": "Bengali Aloo Posto", "type": "VEG", "price": "200.00"},
            {"name": "Delhi Style Butter Chicken", "type": "NON_VEG", "price": "340.00"},
            {"name": "Gujarati Undhiyu", "type": "VEG", "price": "240.00"},
            {"name": "Kashmiri Mutton", "type": "NON_VEG", "price": "440.00"},
            {"name": "Kerala Fish Curry", "type": "NON_VEG", "price": "350.00"},
            {"name": "Maharashtra Pithla Bhakri", "type": "VEG", "price": "160.00"},
            {"name": "Malabar Parotta", "type": "VEG", "price": "60.00"},
            {"name": "Mangalorean Prawn Curry", "type": "NON_VEG", "price": "400.00"},
            {"name": "Punjabi Chole", "type": "VEG", "price": "180.00"},
            {"name": "Rajasthani Chicken", "type": "NON_VEG", "price": "330.00"},
            {"name": "South Indian Sambar", "type": "VEG", "price": "120.00"},
        ],
    },
    {
        "name": "The Vintage Kitchen",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Apple Pie", "type": "VEG", "price": "150.00"},
            {"name": "Bread Pudding", "type": "VEG", "price": "120.00"},
            {"name": "British Raj Chicken Curry", "type": "NON_VEG", "price": "350.00"},
            {"name": "Chicken Cutlet", "type": "NON_VEG", "price": "240.00"},
            {"name": "Club Sandwich", "type": "VEG", "price": "180.00"},
            {"name": "Cottage Cheese Steak", "type": "VEG", "price": "290.00"},
            {"name": "Creamy Mushroom Soup", "type": "VEG", "price": "150.00"},
            {"name": "Fish & Chips", "type": "NON_VEG", "price": "360.00"},
            {"name": "Mashed Potatoes", "type": "VEG", "price": "100.00"},
            {"name": "Railway Mutton Curry", "type": "NON_VEG", "price": "420.00"},
            {"name": "Shepherd's Pie", "type": "NON_VEG", "price": "380.00"},
            {"name": "Veg Cutlet", "type": "VEG", "price": "180.00"},
        ],
    },
    {
        "name": "Wok This Way",
        "location": "Mehsana",
        "dishes": [
            {"name": "Chicken Fried Rice", "type": "NON_VEG", "price": "190.00"},
            {"name": "Chicken Hakka Noodles", "type": "NON_VEG", "price": "200.00"},
            {"name": "Chilli Chicken", "type": "NON_VEG", "price": "280.00"},
            {"name": "Manchurian (Dry/Gravy)", "type": "VEG", "price": "180.00"},
            {"name": "Schezwan Noodles", "type": "VEG", "price": "170.00"},
            {"name": "Spring Rolls", "type": "VEG", "price": "140.00"},
            {"name": "Veg Fried Rice", "type": "VEG", "price": "150.00"},
            {"name": "Veg Hakka Noodles", "type": "VEG", "price": "160.00"},
        ],
    },
    {
        "name": "popes cafe",
        "location": "Himmatnagar",
        "dishes": [
            {"name": "Brownie with Ice Cream", "type": "VEG", "price": "160.00"},
            {"name": "Cappuccino", "type": "VEG", "price": "120.00"},
            {"name": "Cheese Burger", "type": "VEG", "price": "170.00"},
            {"name": "Cheesecake Slice", "type": "VEG", "price": "180.00"},
            {"name": "Chicken BBQ Pizza (8 inch)", "type": "NON_VEG", "price": "340.00"},
            {"name": "Chicken Burger", "type": "NON_VEG", "price": "200.00"},
            {"name": "Chicken Wings (6 pcs)", "type": "NON_VEG", "price": "240.00"},
            {"name": "Classic Burger", "type": "VEG", "price": "140.00"},
            {"name": "Club Sandwich", "type": "VEG", "price": "150.00"},
            {"name": "Cold Coffee", "type": "VEG", "price": "150.00"},
            {"name": "Espresso", "type": "VEG", "price": "80.00"},
            {"name": "French Fries", "type": "VEG", "price": "90.00"},
            {"name": "Grilled Chicken Sandwich", "type": "NON_VEG", "price": "180.00"},
            {"name": "Hot Chocolate", "type": "VEG", "price": "140.00"},
            {"name": "Latte", "type": "VEG", "price": "130.00"},
            {"name": "Margherita Pizza (8 inch)", "type": "VEG", "price": "250.00"},
            {"name": "Nachos with Cheese Dip", "type": "VEG", "price": "170.00"},
            {"name": "Onion Rings", "type": "VEG", "price": "120.00"},
            {"name": "Panini Sandwich", "type": "VEG", "price": "160.00"},
            {"name": "Pepperoni Pizza (8 inch)", "type": "NON_VEG", "price": "360.00"},
            {"name": "Veg Supreme Burger", "type": "VEG", "price": "160.00"},
            {"name": "Veg Supreme Pizza (8 inch)", "type": "VEG", "price": "300.00"},
            {"name": "Waffles", "type": "VEG", "price": "190.00"},
        ],
    },
]
