
import os
import sys
import shutil
import django

# Setup Django environment
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'foodis.settings')
django.setup()

from client.models import Restaurant
from django.conf import settings

def standardize_logos():
    # Define source and destination paths
    media_root = settings.MEDIA_ROOT
    logos_src = os.path.join(media_root, 'restaurants')
    covers_src = os.path.join(logos_src, 'covers')
    
    frontend_public = os.path.join(os.path.dirname(media_root), 'frontend', 'public')
    logos_dest = os.path.join(frontend_public, 'assets', 'restaurants', 'logos')
    covers_dest = os.path.join(frontend_public, 'assets', 'restaurants', 'covers')

    # Ensure destination directories exist
    os.makedirs(logos_dest, exist_ok=True)
    os.makedirs(covers_dest, exist_ok=True)

    print(f"Standardizing logos from {logos_src} to {logos_dest}")
    print(f"Standardizing covers from {covers_src} to {covers_dest}")

    restaurants = Restaurant.objects.all()
    logo_mapping = {}
    cover_mapping = {}
    
    # Helper to normalize names for matching
    def normalize(name):
        return name.lower().replace(' ', '_').replace("'", "").replace("-", "_")

    # Get available files
    logo_files = [f for f in os.listdir(logos_src) if os.path.isfile(os.path.join(logos_src, f))]
    cover_files = [f for f in os.listdir(covers_src) if os.path.isfile(os.path.join(covers_src, f))] if os.path.exists(covers_src) else []

    found_count = 0
    for r in restaurants:
        r_norm = normalize(r.name)
        
        # 1. Match Logo
        logo_match = None
        # Try direct match
        for f in logo_files:
            f_norm = normalize(os.path.splitext(f)[0])
            if f_norm == f"{r_norm}_logo" or f_norm == r_norm:
                logo_match = f
                break
        
        # Try numeric match (restaurant_ID_name.png)
        if not logo_match:
            for f in logo_files:
                if f.startswith(f"restaurant_{r.id}_"):
                    logo_match = f
                    break

        if logo_match:
            ext = os.path.splitext(logo_match)[1]
            shutil.copy2(os.path.join(logos_src, logo_match), os.path.join(logos_dest, f"restaurant_{r.id}{ext}"))
            print(f"LOGGED: {r.name} (ID: {r.id}) logo matched -> {logo_match}")
            logo_mapping[r.id] = f"restaurant_{r.id}{ext}"
            found_count += 1
        
        # 2. Match Cover
        cover_match = None
        for f in cover_files:
            f_norm = normalize(os.path.splitext(f)[0])
            if f_norm == f"{r_norm}_cover":
                cover_match = f
                break
        
        if not cover_match:
            # Check if cover is in logos folder with "cover" in name
            for f in logo_files:
                if "cover" in f.lower() and r_norm in normalize(f):
                    cover_match = f
                    ext = os.path.splitext(f)[1]
                    shutil.copy2(os.path.join(logos_src, cover_match), os.path.join(covers_dest, f"restaurant_{r.id}{ext}"))
                    print(f"COVER: {r.name} (ID: {r.id}) cover matched (from logos) -> {cover_match}")
                    cover_mapping[r.id] = f"restaurant_{r.id}{ext}"
                    break
        elif cover_match:
            ext = os.path.splitext(cover_match)[1]
            shutil.copy2(os.path.join(covers_src, cover_match), os.path.join(covers_dest, f"restaurant_{r.id}{ext}"))
            print(f"COVER: {r.name} (ID: {r.id}) cover matched -> {cover_match}")
            cover_mapping[r.id] = f"restaurant_{r.id}{ext}"

    # Generate JS Mapping file
    js_map_path = os.path.join(os.path.dirname(media_root), 'frontend', 'src', 'utils', 'logo_map.js')
    with open(js_map_path, 'w') as f:
        f.write("/* Auto-generated by logo_standardizer.py */\n")
        f.write("export const RESTAURANT_LOGOS = ")
        f.write(str(logo_mapping))
        f.write(";\n\n")
        f.write("export const RESTAURANT_COVERS = ")
        f.write(str(cover_mapping))
        f.write(";\n")
    
    print(f"\nGenerated JS mapping at {js_map_path}")
    print(f"\nFinished! Standardized {found_count} logos for {restaurants.count()} restaurants.")

if __name__ == "__main__":
    standardize_logos()
